version: "3.8"

services:
  yourapp:
    build:
      context: .
      args:
        HOST: ${HOST:-0.0.0.0}
        PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}" # Expose the app on host's port 8000
    volumes:
      - .:/app/ElectronicsStoreIMS # Mount the project directory to /app/YourProjectName in the container
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
    restart: always
